obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
#robot_radius: 0.17

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap

# The "observation_sources" parameter defines a list of sensors that are going to be passing information to 
# the costmap separated by spaces. Each sensor is defined in the next lines.
#observation_sources: scan
# Definition of the "scan" observation source. Make sure to set the sensor_frame to the same 
# name of the laser frame link that is defined in the robot_description. Otherwise the local costamp won't work.
#scan: {sensor_frame: rplidar_gpu_laser_link, data_type: LaserScan, topic: diffbot/scan, marking: true, clearing: true}
